name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run example
      run: python3 find_lowest_number.py numbers.txt lowest_number.txt
    - name: Test Example
      run: diff lowest_number.txt lowest_expected.txt
    - name: Run test case 1
      run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
    - name: Test Case 1
      run: diff test_data/test1_output.txt test_data/test1_expected.txt
    - name: Run test case 2
      run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
    - name: Test Case 2
      run: diff test_data/test2_output.txt test_data/test2_expected.txt
    - name: Run test case 3
      run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
    - name: Test Case 3
      run: diff test_data/test3_output.txt test_data/test3_expected.txt
